In [5]:
import sys
import numpy as np

# Python Lists are similiar to Python Arrays

In [9]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [15]:
a = np.array([1,2,3,4])

In [13]:
b = np.array([0,.5,.1,2])

In [16]:
a[0], a[1]

(1, 2)

In [17]:
a[0:]

array([1, 2, 3, 4])

In [18]:
a[1:3]

array([2, 3])

In [114]:
a[1:-1]

array([2, 3])

In [20]:
a[::2]

array([1, 3])

In [21]:
b[0], b[2], b[-1]

(0.0, 0.1, 2.0)

In [14]:
b[[0,2,-1]]

array([0. , 0.1, 2. ])

# Array Types

In [24]:
a

array([1, 2, 3, 4])

In [28]:
a.dtype # show data type for integer

dtype('int32')

In [26]:
b

array([0. , 0.5, 0.1, 2. ])

In [ ]:
b.dtype # show data type for float

In [32]:
np.array([1,2,3,4], dtype=np.float) # change type to float

C:\Users\V3n0m\AppData\Local\Temp\ipykernel_23420\129032886.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3,4], dtype=np.float) # change type to float


array([1., 2., 3., 4.])

In [35]:
np.array([1,2,3,4], dtype=np.int8) # change type to int

array([1, 2, 3, 4], dtype=int8)

In [37]:
c = np.array(['a','b','c'])

In [39]:
c.dtype # show data type for a string

dtype('<U1')

In [42]:
d = np.array([{'a':1}, sys])

In [43]:
d.dtype # show data type for a dictionary

dtype('O')

# Dimensions and Shapes

In [44]:
A = np.array([
    [1,2,3],
    [4,5,6]
]) # create an array w/ 2 rows and 2 columns

In [45]:
A.shape # get shape of array in rows, columns

(2, 3)

In [46]:
A.ndim # get number of dimensions of array (horizontal, vertical, etc)

2

In [47]:
A.size # get total number of elements in this array

6

In [50]:
B= np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4],
        [3,2,1]
    ]
]) # create a 3D array (essentially a cube)

In [51]:
B.shape # get size of cube

(2, 2, 3)

In [52]:
B.ndim

3

In [53]:
B.size

12

## NOTE ! IF the shape isn't consistent, it'll fall back to regular Python objects

In [55]:
C = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
    [
        [6,5,4]
    ]
]) # creates an inconsistent array size

C:\Users\V3n0m\AppData\Local\Temp\ipykernel_23420\3320536582.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [56]:
C.dtype

dtype('O')

In [57]:
C.shape

(2,)

In [58]:
C.size

2

In [59]:
type(C[0])

list

# WORKING W/ MATRICES

## Indexing and Slicing  Matrices

In [82]:
# Create a Square Matrix
A = np.array([
#.  0.  1. 2. 
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [64]:
 A[1] # get the 2nd row

array([4, 5, 6])

In [65]:
A[1][0] # get 2nd row first column element

4

## Using multidimensional selection of NumPy: A[d1, d2, d3]

In [ ]:
A[1,0] # get 2nd row first column element

In [67]:
A[0:2] # get all elements in 1st row until not incuding 3rd row | gets everything from range in dimension 1 (d1 = rows)

# Multidimensional selection permits slicing

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
A[:,:2] # gets all rows but only elements up to column 2 (not including)

array([[1, 2],
       [4, 5],
       [7, 8]])

In [71]:
A[:2,:2] # gets elements: all rows up to row 2; all columns up to col 2

array([[1, 2],
       [4, 5]])

In [72]:
A[:2,2:] # gets elements: all rows up to row 2; all columns after col 2

array([[3],
       [6]])

In [73]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

A[1] = np.array([10,10,10]) # change values in 2nd row

In [83]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
A[2] = 99 # change all values in 3rd row

In [87]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

# SUMMARY STATISTICS

In [95]:
a = np.array([1,2,3,4])
a # print array

array([1, 2, 3, 4])

In [91]:
a.sum() # calc sum

10

In [96]:
a.mean() # calc mean

2.5

In [97]:
a.std() # calc standard deviation

1.118033988749895

In [98]:
a.var() # calc variance

1.25

## Applying to a larger Multidimensional Array

In [105]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [99]:
A.sum()

318

In [100]:
A.mean()

35.333333333333336

In [101]:
A.std()

45.04072231510799

In [102]:
A.var()

2028.6666666666667

## Focusing on a Specific Axis Only !

In [106]:
A.sum(axis=0) # gets sum of each columns | axis=0 => columns

array([12, 15, 18])

In [107]:
A.sum(axis=1) # gets sum of each row | axis=1 => rows

array([ 6, 15, 24])

In [110]:
A.mean(axis=0) # gets mean of each row | axis=1 => rows

array([4., 5., 6.])

In [111]:
A.mean(axis=1) # gets mean of each column | axis=1 => rows

array([2., 5., 8.])

In [113]:
A.std(axis=0) # gets standard deviation of each row | axis=1 => rows

array([2.44948974, 2.44948974, 2.44948974])

In [112]:
A.std(axis=1) # gets standard deviation of each row | axis=1 => rows

array([0.81649658, 0.81649658, 0.81649658])