# Boolean Arrays

(also called masks)

In [2]:
import numpy as np

In [7]:
a = np.arange(4)

In [8]:
a

array([0, 1, 2, 3])

In [17]:
print(a[[0,-1]]) # get first and last element
print(a[0], a[-1])

[0 3]
0 3


In [18]:
a[[True, False, False, True]] # get first and last element | Boolean way of saying a[0,-1]

array([0, 3])

In [19]:
a * 10

array([ 0, 10, 20, 30])

In [20]:
a

array([0, 1, 2, 3])

In [21]:
a >= 2 # gets all elements which are greater than 2

array([False, False,  True,  True])

## Filtering | Querying

In [24]:
a[a >= 2] # filtering | querying | pass indices where a>=2 and gets all elements that pass this check

array([2, 3])

In [25]:
a.mean()

1.5

## Get all values which are greater than mean

In [28]:
a[a > a.mean()]

array([2, 3])

In [27]:
a[~(a > a.mean())] # gets all values which are NOT greater than mean

array([0, 1])

In [30]:
a[(a == 0) | (a == 1)] # use '|' to represent OR

array([0, 1])

In [31]:
a[(a <= 2) & (a % 2 == 0)] # use & to represent AND

array([0, 2])

In [33]:
A = np.random.randint(100, size=(3, 3))
A

array([[56, 55, 56],
       [85, 36, 48],
       [30, 72, 35]])

### Convert 3x3 Array into 1D array w/ Boolean Filtering

In [37]:
A[np.array([
    [True, True, True],
    [True, True, True],
    [True, True, True]
])]

array([56, 55, 56, 85, 36, 48, 30, 72, 35])

### Filter out Elements, Leaving a 1D Array

In [38]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([56, 56, 36, 30, 35])

### Create a Booelan Matrix After Result of Operator

In [40]:
A > 30

array([[ True,  True,  True],
       [ True,  True,  True],
       [False,  True,  True]])

### Filter Out Elements which Pass Validation

In [41]:
A[A > 30]

array([56, 55, 56, 85, 36, 48, 72, 35])