# Linear Algebra

In [3]:
import numpy as np

In [4]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [8]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [9]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [10]:
A @ B # @ operator means matrix multiplication !

array([[20, 14],
       [56, 41],
       [92, 68]])

In [13]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [11]:
B.T # transpose matrix

array([[6, 4, 2],
       [5, 3, 1]])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
B.T @ A # tanspose B and dot product A w/ B

array([[36, 48, 60],
       [24, 33, 42]])

# Size of Objects in Memory

## Int, floats

In [15]:
import sys

In [16]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [17]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [18]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [19]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [20]:
np.dtype(float).itemsize

8

## Lists are Even Larger

In [21]:
# A one-element list
sys.getsizeof([1])

64

In [22]:
# An array of one element in numpy
np.array([1]).nbytes

4

##  And performance is also important

In [30]:
l = list(range(100000))

In [29]:
a = np.arange(100000)

In [31]:
%time np.sum(a ** 2)

Wall time: 999 µs


216474736

In [32]:
%time sum([x ** 2 for x in l])

Wall time: 24.9 ms


333328333350000