# Broadcasting and Vectorized Operations


### Broadcasting = refers to how numpy treats arrays with different Dimension during arithmetic operations which lead to certain constraints, the smaller array is broadcast across the larger array so that they have compatible shapes.


### Vectorized Operations = extremely fast operations performed against arrays & arrays, and arrays & scalars

In [5]:
import sys
import numpy as np

In [13]:
a = np.arange(4) #creates an array from 0 to specified number; non-inclusive

In [14]:
a

array([0, 1, 2, 3])

In [15]:
a + 10 # sum the entire array by 10

array([10, 11, 12, 13])

In [16]:
a * 10 # mult the entire array by 10

array([ 0, 10, 20, 30])

### Notice the original array is unchanged due to arrays being immutable in Python.

#### The product of your arithmtic values are all stored in a *new* array.

In [18]:
a

array([0, 1, 2, 3])

In [21]:
l = [0,1,2,3]
l

[0, 1, 2, 3]

In [22]:
[i * 10 for i in l] # mults every element in l by 10

[0, 10, 20, 30]

In [23]:
a = np.arange(4)

In [27]:
a

array([0, 1, 2, 3])

In [28]:
b = np.array([10,10,10,10])

In [29]:
a + b # adds each element with the respective index

array([10, 11, 12, 13])

In [30]:
a * b # mults each element with the respective index

array([ 0, 10, 20, 30])