# NumPy Exercises

In [3]:
import numpy as np

## Array Creation

### Create a numpy array of size 10, filled w/ zeros.

In [16]:
a = np.arange(10)
a * 0

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.array([0] * 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Create a numpy array with values ranging from 10 to 49

In [31]:
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Create a numpy matrix of 2*2 integers, filled with ones.

In [30]:
np.ones([2,2], dtype=int)

array([[1, 1],
       [1, 1]])

In [ ]:
### any others ways?
#a = np.array([1,1] * [2,2])?

### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [41]:
np.ones([3,2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [44]:
X = np.arange(4, dtype=int)

np.ones_like(X)

array([1, 1, 1, 1])

### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [47]:
X = np.arange(4, dtype=int)
np.zeros_like(X)

array([0, 0, 0, 0])

In [48]:
# OR w/ a larger array

X = np.array([[1,2,3], [4,5,6]], dtype=int)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

 ### Create a numpy matrix of 4*4 integers, filled with fives.

In [52]:
# Cumbersome method
np.array([
    [5,5,5],
    [5,5,5],
    [5,5,5],
    [5,5,5]
])

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [69]:
# Better Method
np.ones([4,4]) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

###  Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [75]:
X = np.arange(4, dtype=int)
X
Y = np.ones_like(X) * 7
Y

array([7, 7, 7, 7])

###  Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
# OR
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###  Create a numpy array, filled with 3 random integer values between 1 and 10.

In [83]:
np.random.randint(10, size=3)

array([4, 0, 6])

### Create a 3x3x3 numpy matrix, filled with random float values.

In [107]:
np.random.random((3,3,3))  # 0 to 1 floats

array([[[0.24129349, 0.76689198, 0.59759271],
        [0.16138797, 0.04509793, 0.83231043],
        [0.05920824, 0.44011543, 0.07970695]],

       [[0.2810702 , 0.7798252 , 0.58017032],
        [0.5797253 , 0.86946531, 0.77694427],
        [0.16833863, 0.30156129, 0.37076644]],

       [[0.67218148, 0.80600857, 0.22497273],
        [0.84459792, 0.09657336, 0.11098854],
        [0.21138445, 0.86306298, 0.28323141]]])

In [ ]:
# OR

In [95]:
np.random.randn(3,3,3) # 0 to 1 floats

array([[[-0.81455817,  0.32542683,  0.15825732],
        [-0.36398861, -0.60871036,  1.09358598],
        [ 1.0228984 , -0.10493251,  0.26779053]],

       [[ 0.13478296, -1.37375896,  0.08877828],
        [-0.39167202,  1.07301549,  1.54290966],
        [ 0.57669041, -0.4763854 ,  1.14730793]],

       [[-1.40655226,  1.00455887, -0.35916569],
        [ 1.33936988,  0.27330062, -0.35856162],
        [ 0.74079172,  2.8670863 , -0.15033119]]])

 ### Given the X python list convert it to an Y numpy array

In [120]:
X = list([1,2,3]) # or X = [1,2,3]
print(f"X = {X} is data type {type(X)}")
Y = np.array(X)
print(f"Y = {Y} is data type {type(Y)}")

X = [1, 2, 3] is data type <class 'list'>
Y = [1 2 3] is data type <class 'numpy.ndarray'>


###  Given the X numpy array, make a copy and store it on Y.

In [125]:
X = np.array([5,2,3], dtype=int)
print(X, id(X)) # show the id

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 2298387562288
[5 2 3] 2298387516848


### Create a numpy array with numbers from 1 to 10

In [132]:
X = np.arange(11)
X[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### OR

In [134]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###  Create a numpy array with numbers from 1 to 10, in descending order.

In [138]:
np.arange(1, 11)[::-1] # reorganize the array afrterwards

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [143]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Show the memory size of the given Z numpy matrix

In [145]:
Z = np.zeros((10,10))

print("%d bytes" % (Z.size * Z.itemsize))

800 bytes
