# Array Manipulation

### Convert the given integer numpy array to float

In [2]:
import numpy as np

In [5]:
X = [-5, -3, 0, 10, 40]

np.array(X, float)

array([-5., -3.,  0., 10., 40.])

### Reverse the given numpy array (first element becomes last)

In [6]:
X[::-1]

[40, 10, 0, -3, -5]

### Order (sort) the given numpy array

In [9]:
X = [-20,4,55,-11]
np.sort(X)

array([-20, -11,   4,  55])

### Given the X numpy array, set the fifth element equal to 1

In [10]:
X = np.arange(6)
X[4] = 1
X

array([0, 1, 2, 3, 1, 5])

###  Given the X numpy array, change the 50 with a 40

In [11]:
X = np.array([10, 20, 30, 50])

X[3] = 40
X

array([10, 20, 30, 40])

### Given the X numpy matrix, change the last row with all 1

In [19]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = np.array([1, 1, 1, 1])
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

### Given the X numpy matrix, change the last item on the last row with a 0

In [21]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1,-1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

### Given the X numpy matrix, add 5 to every element

In [22]:
X + 5

array([[ 6,  7,  8,  9],
       [10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20,  5]])