# Array Indexation

In [2]:
import numpy as np

###  Given the X numpy array, show it's first element

In [4]:
X = np.arange(4)
X[0]

0

###  Given the X numpy array, show it's last element

In [5]:
X[-1]

3

OR

In [7]:
X[len(X)-1]

3

### Given the X numpy array, show it's first three elements

In [8]:
X[0:3]

array([0, 1, 2])

###  Given the X numpy array, show all middle elements

In [11]:
X[1:len(X)-1]

array([1, 2])

OR

In [14]:
X[1:-1]

array([1, 2])

###  Given the X numpy array, show the elements in reverse position

In [18]:
X[::-1]

array([3, 2, 1, 0])

###  Given the X numpy array, show the elements in an odd position

In [20]:
X[::2]

array([0, 2])

OR

### Given the X numpy matrix, show the first row elements

In [36]:
#X = np.ones([2,2], dtype=int) # Note: w/o specifying - ones function creates floats
X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("X =\n", X)

X[0]

X =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3])

### Given the X numpy matrix, show the last row elements

In [37]:
X[-1]

array([7, 8, 9])

### Given the X numpy matrix, show the first element on first row

In [38]:
X[0][0]

1

OR

In [39]:
X[0,0]

1

### Given the X numpy matrix, show the last element on last row

In [40]:
X[-1,-1]

9

OR

In [41]:
X[-1][-1]

9

### Given the X numpy matrix, show the middle row elements

In [50]:
X = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(X)

X[1:-1,1:-1]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[5]])

In [47]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])


X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

### Given the X numpy matrix, show the first two elements on the first two rows

In [51]:
X[0:2,0:2]

array([[1, 2],
       [4, 5]])

OR

In [52]:
X[:2,:2]

array([[1, 2],
       [4, 5]])

### Given the X numpy matrix, show the last two elements on the last two rows

In [58]:
#X[len(X[0]-1)] # TODO: Get this to work later!

X[1:, 1:]

array([[5, 6],
       [8, 9]])